// Code Owner: fayeblade (@spearchucker667)
// Image generation preview + recent history — extracted from ImageModule.
import React from "react";
import { CollapsibleSection } from "./CollapsibleSection";
import { GalleryImage } from "../types/storage";
import { ModuleProps, ImageDraft } from "../types/app";

interface ImageGenerationPreviewProps extends ModuleProps {
  draft: ImageDraft;
  recentHistory: GalleryImage[];
  onExpand: (img: GalleryImage) => void;
  onLoadSettings: (img: GalleryImage) => void;
}

export function ImageGenerationPreview({
  state,
  dispatch,
  draft,
  recentHistory,
  onExpand,
  onLoadSettings,
}: ImageGenerationPreviewProps) {
  function patch(updates: Partial<ImageDraft>) {
    dispatch({ type: "SET_IMAGE_DRAFT", patch: updates });
  }

  function buildFallbackImage(): GalleryImage {
    return {
      id: draft.lastSavedImageId || "preview",
      image: draft.currentImage!,
      prompt: draft.prompt,
      model: state.selectedImageModel,
      timestamp: Date.now(),
    };
  }

  return (
    <>
      <div className="space-y-3">
        <div className="flex min-h-[200px] items-center justify-center overflow-hidden rounded-2xl border border-border/50 bg-surface/40">
          {draft.generationProgress ? (
            <div className="flex flex-col items-center gap-3 p-6">
              <div className="text-sm text-text-secondary">{draft.generationProgress}</div>
              <div className="h-1.5 w-48 overflow-hidden rounded-full bg-surface-elevated">
                <div className="h-full w-1/2 animate-pulse rounded-full bg-gradient-to-r from-accent to-accent-hover" />
              </div>
            </div>
          ) : draft.currentImages && draft.currentImages.length > 1 ? (
            <div className={`grid gap-2 p-2 ${draft.currentImages.length <= 2 ? "grid-cols-2" : draft.currentImages.length <= 4 ? "grid-cols-2" : "grid-cols-3"}`}>
              {draft.currentImages.map((savedDoc: GalleryImage, idx: number) => (
                <button
                  key={savedDoc.id || idx}
                  onClick={() => onExpand(savedDoc)}
                  className="overflow-hidden rounded-xl border border-border/50 transition-all duration-200 hover:scale-[1.02] hover:border-accent/30 hover:shadow-[0_0_16px_var(--glow)] focus:outline-none focus:ring-2 focus:ring-accent/50"
                  aria-label={`View image details: ${savedDoc.prompt || "Generated image"}`}
                >
                  <img
                    src={savedDoc.image}
                    alt={`Generated by Venice ${idx + 1}`}
                    className="aspect-square w-full object-cover"
                  />
                </button>
              ))}
            </div>
          ) : draft.currentImage ? (
            <button
              onClick={() => {
                const found = state.gallery.find((x: GalleryImage) => x.id === draft.lastSavedImageId);
                onExpand(found || buildFallbackImage());
              }}
              className="overflow-hidden transition-all duration-200 hover:scale-[1.01] focus:outline-none focus:ring-2 focus:ring-accent/50"
              aria-label="View generated image details"
            >
              <img src={draft.currentImage} alt="Generated by Venice" className="max-h-[500px] object-contain" />
            </button>
          ) : (
            <div className="p-12 text-sm text-text-muted">Generated image preview</div>
          )}
        </div>
        <div className="text-xs text-text-muted">
          Prompt and controls persist when switching menus. Generated images
          auto-save to Gallery.
        </div>
      </div>

      {recentHistory.length > 0 && (
        <div className="mt-4 px-1">
          <CollapsibleSection title="Recent Prompts & Settings" defaultOpen={false}>
            <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
              {recentHistory.map((img) => (
                <div
                  key={img.id}
                  className="flex items-center gap-3 rounded-2xl border border-border/50 bg-surface-elevated/40 p-4 backdrop-blur-sm transition-all duration-200 hover:border-border hover:bg-surface-elevated"
                >
                  <img
                    src={img.image}
                    alt=""
                    className="h-16 w-16 shrink-0 rounded-xl object-cover"
                  />
                  <div className="min-w-0 flex-1">
                    <div className="truncate text-sm font-medium text-text-primary">
                      {img.prompt}
                    </div>
                    <div className="mt-0.5 text-xs text-text-muted">
                      {img.model} • {img.aspectRatio || `${img.width}x${img.height}`}
                    </div>
                    <div className="mt-2 flex gap-2">
                      <button className="btn" onClick={() => onLoadSettings(img)}>
                        Load Settings
                      </button>
                      <button
                        className="btn"
                        onClick={() => {
                          patch({ prompt: img.prompt });
                          dispatch({
                            type: "ADD_TOAST",
                            toast: { id: crypto.randomUUID(), message: "Copied prompt", type: "info" },
                          });
                        }}
                      >
                        Copy Prompt
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </CollapsibleSection>
        </div>
      )}
    </>
  );
}
